[server]
host = "localhost"
port = "5050"
token = "#{SPOTIFY_SERVER_TOKEN}"
prefork = false
timeZone = "America/Caracas"

[socket]
origins = ["*"]
readBufferSize = 2048
writeBufferSize = 2048

[spotify]
clientID = "#{SPOTIFY_CLIENT_ID}"
clientSecret = "#{SPOTIFY_CLIENT_SECRET}"
refreshToken = "#{SPOTIFY_REFRESH_TOKEN}"
